### ISSUE TITLE
General fixes

### ISSUE THREAD

**Issue by abdelazizElemary** [El-Nebo/Frontend-Udemy-Welcome-Page#1]
- fix the nav bar items responsively 
<img width="1440" alt="Screen Shot 2022-08-11 at 11 54 48 AM" src="https://user-images.githubusercontent.com/25887879/184109099-358c84bb-96ea-475c-a366-8e32e8550f73.png">

- fix widths for buttons in the nav bar as well

**Comment by El-Nebo** [comment]
Done.
